apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  namespace: todoapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: ikulyk404/todoapp:3.0.0
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"
          env:
            - name: PYTHONUNBUFFERED
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PYTHONUNBUFFERED
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-db-secret
                  key: HOST
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: api/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: api/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
