apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_USER: dG9kb191c2Vy
  MYSQL_PASSWORD: dG9kb19wYXNzd29yZA==
  MYSQL_DATABASE: dG9kb2FwcA==
---
apiVersion: v1
kind: Secret
metadata:
  name: app-db-secret
  namespace: todoapp
type: Opaque
data:
  NAME: dG9kb2FwcA==
  USER: dG9kb191c2Vy
  PASSWORD: dG9kb19wYXNzd29yZA==
  HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbA==
